
#include %A_WorkingDir%\local_code_location.ahk
SetWorkingDir path
; Admin
; Standard
Run "balders_game.ahk"
Run "chained_echoes.ahk"
Run "email.ahk"
Run "factorio.ahk"
Run "grim_dawn.ahk"
Run "last_epoch.ahk"
Run "on_top.ahk"
Run "path_of_exile.ahk"
Run "starcraft.ahk"
Run "terrorhedron.ahk"
Run "unity.ahk"
Run "utils.ahk"
Run "vampire_survivors.ahk"
;Run "leaf_blower.ahk"
